//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheapLoansWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanNum { get; set; }
        public string CustName { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal AnnualIntRate { get; set; }
        public int NumPayments { get; set; }
    }
}
